/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ProductCard {
        "description": string;
        "img": string;
        "name": string;
        "price": number | string;
    }
    interface ProductContainer {
    }
    interface ToggleFavourite {
        "buttonColor": string;
        "text": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLProductCardElement extends Components.ProductCard, HTMLStencilElement {
    }
    var HTMLProductCardElement: {
        prototype: HTMLProductCardElement;
        new (): HTMLProductCardElement;
    };
    interface HTMLProductContainerElement extends Components.ProductContainer, HTMLStencilElement {
    }
    var HTMLProductContainerElement: {
        prototype: HTMLProductContainerElement;
        new (): HTMLProductContainerElement;
    };
    interface HTMLToggleFavouriteElement extends Components.ToggleFavourite, HTMLStencilElement {
    }
    var HTMLToggleFavouriteElement: {
        prototype: HTMLToggleFavouriteElement;
        new (): HTMLToggleFavouriteElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "product-card": HTMLProductCardElement;
        "product-container": HTMLProductContainerElement;
        "toggle-favourite": HTMLToggleFavouriteElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ProductCard {
        "description"?: string;
        "img"?: string;
        "name"?: string;
        "price"?: number | string;
    }
    interface ProductContainer {
    }
    interface ToggleFavourite {
        "buttonColor"?: string;
        "onToggleFavourite"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "product-card": ProductCard;
        "product-container": ProductContainer;
        "toggle-favourite": ToggleFavourite;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "product-card": LocalJSX.ProductCard & JSXBase.HTMLAttributes<HTMLProductCardElement>;
            "product-container": LocalJSX.ProductContainer & JSXBase.HTMLAttributes<HTMLProductContainerElement>;
            "toggle-favourite": LocalJSX.ToggleFavourite & JSXBase.HTMLAttributes<HTMLToggleFavouriteElement>;
        }
    }
}
